SELECT a.PRODUCT_CODE, SUM(b.cnt) AS SALES
FROM PRODUCT AS a INNER JOIN (SELECT SUM(b.SALES_AMOUNT) * a.PRICE AS cnt, a.PRODUCT_CODE
                            FROM PRODUCT AS a INNER JOIN OFFLINE_SALE AS b
                            ON a.PRODUCT_ID = b.PRODUCT_ID
                            GROUP BY a.PRODUCT_CODE, a.PRICE) AS b
ON a.PRODUCT_CODE = b.PRODUCT_CODE  
GROUP BY LEFT(a.PRODUCT_CODE, 2), a.PRODUCT_CODE
ORDER BY SALES DESC, a.PRODUCT_CODE