SELECT CAR_ID, a.CAR_TYPE, DAILY_FEE * 30 * (1 - discount_rate / 100) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS a INNER JOIN (SELECT a.CAR_ID, CAR_TYPE, DAILY_FEE
      FROM CAR_RENTAL_COMPANY_CAR AS a INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS b
      ON a.CAR_ID = b.CAR_ID 
      WHERE (CAR_TYPE = '세단' OR CAR_TYPE = 'SUV')
      GROUP BY a.CAR_ID, CAR_TYPE, DAILY_FEE
      HAVING MAX(END_DATE) < '2022-11-1')AS b
ON a.CAR_TYPE = b.CAR_TYPE
WHERE duration_type = '30일 이상' AND DAILY_FEE * 30 * (1 - discount_rate / 100) >= 500000 AND
      DAILY_FEE * 30 * (1 - discount_rate / 100) < 2000000
ORDER BY FEE DESC, a.CAR_TYPE ASC, CAR_ID DESC