SELECT MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM MEMBER_PROFILE AS a INNER JOIN REST_REVIEW AS b
ON a.MEMBER_ID = b.MEMBER_ID
WHERE a.MEMBER_ID = (SELECT MEMBER_ID
                    FROM REST_REVIEW 
                    GROUP BY MEMBER_ID
                    ORDER BY COUNT(MEMBER_ID) DESC
                    LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT                    