SELECT BOOK_ID, AUTHOR_NAME, PUBLISHED_DATE
FROM AUTHOR AS a INNER JOIN (SELECT AUTHOR_ID, BOOK_ID, PUBLISHED_DATE
                            FROM BOOK 
                            WHERE CATEGORY IN ('경제')) AS b
ON a.AUTHOR_ID = b.AUTHOR_ID       
ORDER BY PUBLISHED_DATE